plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace 'com.cosinetech.imates'
    compileSdk 34

    defaultConfig {
        applicationId "com.cosinetech.imates"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
        compose true
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.recyclerview
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.lifecycle.runtime.ktx
    implementation libs.activity.compose
    implementation platform(libs.compose.bom)
    implementation libs.ui
    implementation libs.ui.graphics
    implementation libs.ui.tooling.preview
    implementation libs.material3
    implementation libs.annotation
    implementation libs.leanback
    implementation libs.activity
    implementation libs.lottie
    implementation libs.refresh.layout.kernel // 核心库
    implementation libs.refresh.header.classics // 经典 Header
    implementation libs.refresh.footer.classics // 经典 Footer
    // Markwon dependencies
    implementation libs.core
    implementation libs.image
    implementation libs.image.glide
    implementation libs.ext.latex
    implementation libs.glide.v4120
    implementation libs.compiler
//    implementation libs.jlatexmath
    // http/https请求库
    implementation platform(libs.okhttp.bom)
    // define any required OkHttp artifacts without version
    implementation libs.okhttp
    implementation libs.logging.interceptor
    // ========
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.ui.test.junit4
    debugImplementation libs.ui.tooling
    debugImplementation libs.ui.test.manifest
}