import groovy.json.JsonBuilder
import java.security.MessageDigest

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace 'com.cosinetech.imates'
    compileSdk 34

    defaultConfig {
        applicationId "com.cosinetech.imates"
        minSdk 24
        targetSdk 34
        versionCode 22
        versionName "1.0.22"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // 配置APK输出路径和名称
    android.applicationVariants.all { variant ->
        def buildTypeName = variant.buildType.name // 获取构建类型名称
        def outputs = variant.outputs
        outputs.all { output ->
            if (output.outputFile != null && output.outputFile.name.endsWith('.apk')) {
                def versionName = variant.versionName
                def versionCode = variant.versionCode

                // 定义输出文件的新名称
                def outputFileName = "app-${versionName}-${versionCode}.apk"

                // 修改 APK 文件的输出路径和文件名
                output.outputFileName = outputFileName
            }
        }

        // 配置assemble任务以改变输出目录
        variant.assembleProvider.configure { task ->
            task.doLast {
                outputs.each { output ->
                    if (output.outputFile != null && output.outputFile.name.endsWith('.apk')) {
                        def originalOutputFile = output.outputFile
                        def newOutputDir = new File(rootProject.projectDir, 'output/' + buildTypeName)
                        def newOutputFile = new File(newOutputDir, originalOutputFile.name)

                        // 确保输出目录存在
                        newOutputDir.mkdirs()

                        // 复制APK到新的输出目录
                        copy {
                            from originalOutputFile
                            into newOutputDir
                        }

                        // 如果需要删除旧的APK文件，可以取消注释以下行
                        // originalOutputFile.delete()

                        // 计算文件大小和MD5校验码
                        def fileSize = newOutputFile.length()
                        def md5Checksum = calculateMd5(newOutputFile)

                        // 创建该APK对应的JSON信息
                        def apkInfo = [
                                fileName: newOutputFile.name,
                                filePath: newOutputFile.absolutePath,
                                fileSize: fileSize,
                                md5Checksum: md5Checksum
                        ]

                        // 创建JSON文件，并保存在与APK相同的目录下
                        def jsonFileName = "${newOutputFile.name.replace('.apk', '')}-info.json"
                        def jsonFile = new File(newOutputDir, jsonFileName)
                        jsonFile.text = new JsonBuilder(apkInfo).toPrettyString()
                    }
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
        compose true
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

// 辅助方法：计算文件的MD5校验码
def calculateMd5(File file) {
    def md5 = MessageDigest.getInstance("MD5")
    file.withInputStream { inputStream ->
        byte[] buffer = new byte[8192]
        int bytesRead
        while ((bytesRead = inputStream.read(buffer)) != -1) {
            md5.update(buffer, 0, bytesRead)
        }
    }
    return md5.digest().encodeHex().toString()
}

dependencies {
    implementation fileTree(dir: "libs", include: [".jar", ".aar"])

    implementation libs.appcompat
    implementation libs.material
    implementation libs.recyclerview
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.lifecycle.runtime.ktx
    implementation libs.activity.compose
    implementation platform(libs.compose.bom)
    implementation libs.ui
    implementation libs.ui.graphics
    implementation libs.ui.tooling.preview
    implementation libs.material3
    implementation libs.annotation
    implementation libs.leanback
    implementation libs.activity

    implementation libs.gson

    // ======== lottie animate ========
    implementation libs.lottie

    // ======== smartrefreshlayout ========
    implementation libs.refresh.layout.kernel // 核心库
    implementation libs.refresh.header.classics // 经典 Header
    implementation libs.refresh.footer.classics // 经典 Footer

    // ======== markdown dependencies ========
    implementation libs.commonmark
    implementation libs.commonmark.parent
    implementation 'com.atlassian.commonmark:commonmark-ext-gfm-tables:0.13.0'
    implementation libs.jlatexmath.android
    implementation libs.jlatexmath.android.font.cyrillic
    implementation libs.jlatexmath.android.font.greek
    implementation files('libs/markwon-core.aar')
    implementation files('libs/markwon-html.aar')
    implementation files('libs/markwon-ext-tables.aar')
    implementation files('libs/markwon-image.aar')
    implementation files('libs/markwon-image-glide.aar')
    implementation files('libs/markwon-inline-parser.aar')
    implementation files('libs/markwon-syntax-highlight.aar')
    implementation files('libs/markwon-ext-latex.aar')
//    implementation libs.core
//    implementation libs.image
//    implementation libs.image.glide
//    implementation libs.ext.latex
    implementation libs.glide.v4120
    implementation libs.compiler

    // ======== CameraX core library ========
    def camerax_version = "1.4.0" // 使用最新版本号
    implementation libs.camera.core
    implementation libs.camera.camera2
    implementation libs.camera.lifecycle
    implementation libs.camera.view
    implementation libs.android.image.cropper

    // ======== http/https请求库 ========
    implementation platform(libs.okhttp.bom)
    // define any required OkHttp artifacts without version
    implementation libs.okhttp
    implementation libs.logging.interceptor

    // ======== Viewer pager for tab layout
    implementation libs.viewpager2
    implementation libs.material.v175

    // ======== graph view
    implementation libs.graphview

    // ======== pdf
    implementation 'com.github.mhiew:android-pdf-viewer:3.2.0-beta.1'

    implementation 'com.github.sendtion:XRichText:1.9.4'

    implementation 'com.github.chrisbanes:PhotoView:2.3.0'

    // ======== rating
    implementation libs.simpleratingview

    // ======= easy floating tool
    implementation libs.easyfloat

    // =======photo editor
    //implementation 'com.burhanrashid52:photoeditor:3.0.2'

    implementation 'io.github.litao0621:nifty-slider:2.0.2'
    implementation 'androidx.webkit:webkit:1.4.0'

    implementation 'com.github.xuexiangjys:XUpdate:2.1.2'
    implementation 'com.github.xuexiangjys.XUpdateAPI:xupdate-easy:1.0.1'

    implementation 'com.rabbitmq:amqp-client:5.13.0'
    implementation 'com.google.guava:guava:30.1.1-android'

    implementation project(path: ':pdflibrary')
    implementation project(path: ':image')

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.ui.test.junit4
    debugImplementation libs.ui.tooling
    debugImplementation libs.ui.test.manifest
}